name: Rust CI

on:
  workflow_dispatch: # Allows manual workflow execution from the GitHub interface

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build project
        run: cargo build --verbose

      - name: Run Unit Tests
        run: cargo test --verbose
